### ISSUE TITLE
Macro F1 smaller than 0.5

### ISSUE THREAD

**Issue by JunwenBai** [yankeesrules/C2AE#2]
Correct me if I'm wrong. But from what I know, a random classifier gives 0.5 F1-score. The reported  macro-F1 score is even lower than 0.5. Does it mean the C2AE is even worse than a random predictor? How to explain the result? Thx!

**Comment by chihkuanyeh** [comment]
Hi @GilbertHeywood, I would have to disagree that a random classifier gives 0.5 F1-score. The micro-F1 for labels with 0.5 probability positive gives 0.5 micro-F1, but in practice, the positive label for multi-label is sparse. In the case where 1/10 of the label is positive and others are negative, random classifiers give less than 0.2 micro-F1 (depending on the positive rate). Therefore, the result from C2AE is much better than random since there is a sparse percentage of positive labels in the data.

**Comment by JunwenBai** [comment]
However, all pos or all neg classifiers are also trivial classifiers, right? Let's take your example and say 1/10 is NEG and 9/10 is POS. My predictor gives all pos. Then precision = 0.9 and recall=1. F1=0.947. In a more balanced data, F1 could drop to around 0.5. Is it just a convention that we typically only compare to random predictors as a baseline?

**Comment by chihkuanyeh** [comment]
@GilbertHeywood I would have to respectfully disagree with your comment. In my example, 1/10 is POS and 9/10 is NEG (since multi-label datasets are sparse as in almost all datasets). An all pos predictor gets micro-F1 score of 0.182, and an all neg predictor gets micro-F1 score of 0, which are all less than 0.2 micro-F1 as I have mentioned. In practice, the actual label is often sparser than having 1/10 positive label, and macro-F1 is often lower than micro-F1. Therefore, the result of C2AE and all baselines are indeed much better than any trivial classifiers.
